"""Thin client for the public vulkan.gpuinfo.org API
(https://github.com/SaschaWillems/vulkan.gpuinfo.org/blob/master/docs/api.md).

Proof-of-concept status: this calls the *public* API, which its own docs
say isn't meant for building an application on top of ("don't use it for
creating your own applications", "don't excessively request data" without
asking first) -- fine for now per explicit agreement to stay in POC scope,
but before this goes beyond that, ask the maintainer for consent (or for
access to something closer to the unstable `api/internal` endpoints), same
as planned for a bulk-data need. See docs-index/README.md.

Caches every response to disk (keyed by request URL, no expiry) specifically
to avoid repeat-querying the same report/coverage data -- being a considerate
citizen of a single hobbyist-funded server matters here more than staying
fresh. Report data for a shipped device doesn't change; delete the cache
directory to force a refetch.
"""

from __future__ import annotations

import hashlib
import json
import os
import time
import urllib.error
import urllib.parse
import urllib.request

from config import CACHE_ROOT

API_BASE = "https://vulkan.gpuinfo.org/api"
_CACHE_DIR = os.path.join(CACHE_ROOT, "gpuinfo")
_USER_AGENT = "mcpVulkan-docs-index/0.1 (proof-of-concept; see docs-index/README.md)"


class GpuinfoError(Exception):
    """Raised when the API call fails -- includes the HTTP status when known."""


def _cache_path(url: str) -> str:
    digest = hashlib.sha256(url.encode()).hexdigest()
    return os.path.join(_CACHE_DIR, f"{digest}.json")


def _get_json(url: str, ttl_seconds: float | None = None) -> dict:
    """ttl_seconds=None means cache forever (right for a single device's
    immutable report/profile); a driver-coverage query's result set grows
    as new reports are submitted, so those calls pass a TTL instead.
    """
    cache_path = _cache_path(url)
    if os.path.isfile(cache_path):
        if ttl_seconds is None or (time.time() - os.path.getmtime(cache_path)) < ttl_seconds:
            with open(cache_path, encoding="utf-8") as f:
                return json.load(f)

    req = urllib.request.Request(url, headers={"User-Agent": _USER_AGENT})
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            # strict=False: some device-submitted fields (e.g. free-text
            # driver/device names) contain literal control characters the
            # API doesn't escape, which json.loads rejects by default.
            data = json.loads(resp.read(), strict=False)
    except urllib.error.HTTPError as e:
        raise GpuinfoError(f"HTTP {e.code} from {url}") from e
    except urllib.error.URLError as e:
        raise GpuinfoError(f"could not reach {url}: {e}") from e

    os.makedirs(_CACHE_DIR, exist_ok=True)
    with open(cache_path, "w", encoding="utf-8") as f:
        json.dump(data, f)
    return data


def get_report(report_id: int) -> dict:
    """Full capability report for one submitted device (extensions,
    features, properties/limits, formats, ...). GET /api/v2/getreport.
    """
    return _get_json(f"{API_BASE}/v2/getreport?id={report_id}")


def get_profile(report_id: int) -> dict:
    """Ready-made Vulkan Profile JSON for one report, as generated by the
    database itself (for use with LunarG's Vulkan Profiles Layer). GET
    /api/v3/getprofile. As of this client being written, this endpoint was
    returning HTTP 500 for every report_id tried -- looks broken
    server-side, not a client-side issue. Prefer build_profile_from_reports
    (in profile_builder.py) for now, which builds an equivalent profile
    from get_report() data, which does work.
    """
    return _get_json(f"{API_BASE}/v3/getprofile?id={report_id}")


_COVERAGE_PATHS = {
    "extension": ("extension", "extension"),
    "feature": ("feature", "feature"),
    "feature2": ("feature2", None),  # needs both extension= and feature=
    # The API docs' endpoint table says "drivercoverage/presentmode", but
    # that 404s -- their own worked example uses "surface/presentmode",
    # which is what actually works. Docs bug, not ours.
    "presentmode": ("surface/presentmode", "presentmode"),
    "subgroup_stage": ("subgroups/stage", "stage"),
    "subgroup_operation": ("subgroups/operation", "operation"),
}


def driver_coverage(kind: str, value: str, extension: str | None = None, platform: str | None = None) -> dict:
    """Devices + first known driver version supporting a given extension,
    feature, extension-feature pair, present mode, or subgroup
    stage/operation. `kind` is one of extension/feature/feature2/
    presentmode/subgroup_stage/subgroup_operation; `value` is the
    extension/feature/presentmode/stage/operation name (for feature2,
    `value` is the feature name and `extension` names the extension it
    belongs to). `platform` optionally limits to windows/linux/android.
    """
    if kind not in _COVERAGE_PATHS:
        raise ValueError(f"unknown coverage kind {kind!r}; expected one of {sorted(_COVERAGE_PATHS)}")
    path, param_name = _COVERAGE_PATHS[kind]

    params: dict[str, str] = {}
    if kind == "feature2":
        if not extension:
            raise ValueError("kind='feature2' requires `extension` (the extension the feature belongs to)")
        params["extension"] = extension
        params["feature"] = value
    else:
        params[param_name] = value
    if platform:
        params["platform"] = platform

    url = f"{API_BASE}/v2/drivercoverage/{path}?{urllib.parse.urlencode(params)}"
    return _get_json(url, ttl_seconds=24 * 3600)
